// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::MeshRenderer>
    : TypeInfoBase<My::MyGE::MeshRenderer> {
#ifdef MY_MYSREFL_NOT_USE_NAMEOF
  static constexpr char name[27] = "My::MyGE::MeshRenderer";
#endif
  static constexpr AttrList attrs = {};
  static constexpr FieldList fields = {
      Field{TSTR("materials"), &Type::materials},
  };
};
