// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::Skybox>
    : TypeInfoBase<My::MyGE::Skybox> {
#ifdef MY_MYSREFL_NOT_USE_NAMEOF
  static constexpr char name[21] = "My::MyGE::Skybox";
#endif
  static constexpr AttrList attrs = {};
  static constexpr FieldList fields = {
      Field{TSTR("material"), &Type::material},
  };
};
