// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyECS::AccessMode>
    : My::MySRefl::TypeInfoBase<My::MyECS::AccessMode> {
  static constexpr AttrList attrs = {};

  static constexpr FieldList fields = {
      Field{"LAST_FRAME", My::MyECS::AccessMode::LAST_FRAME},
      Field{"WRITE", My::MyECS::AccessMode::WRITE},
      Field{"LATEST", My::MyECS::AccessMode::LATEST},
  };
};
