// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::LuaScriptQueue>
    : TypeInfoBase<My::MyGE::LuaScriptQueue> {
#ifdef MY_MYSREFL_NOT_USE_NAMEOF
  static constexpr char name[29] = "My::MyGE::LuaScriptQueue";
#endif
  static constexpr AttrList attrs = {};
  static constexpr FieldList fields = {
      Field{TSTR("value"), &Type::value},
  };
};
