// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template<>
struct My::MySRefl::TypeInfo<My::MyGE::Children> :
    TypeInfoBase<My::MyGE::Children>
{
#ifdef MY_MYSREFL_NOT_USE_NAMEOF
    static constexpr char name[19] = "My::MyGE::Children";
#endif
    static constexpr AttrList attrs = {};
    static constexpr FieldList fields = {
        Field {TSTR("value"), &Type::value},
    };
};

