// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::MeshRenderer>
    : My::MySRefl::TypeInfoBase<My::MyGE::MeshRenderer> {
  static constexpr AttrList attrs = {};

  static constexpr FieldList fields = {
      Field{"material", &My::MyGE::MeshRenderer::material},
  };
};