// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::MeshFilter>
    : My::MySRefl::TypeInfoBase<My::MyGE::MeshFilter> {
  static constexpr AttrList attrs = {};

  static constexpr FieldList fields = {
      Field{"mesh", &My::MyGE::MeshFilter::mesh},
  };
};