// This file is generated by My::MySRefl::AutoRefl
 
#pragma once
 
#include <MySRefl/MySRefl.h>
 
template<>
struct My::MySRefl::TypeInfo<My::MyGE::Name>
    : My::MySRefl::TypeInfoBase<My::MyGE::Name>
{
  static constexpr AttrList attrs = {};
 
  static constexpr FieldList fields = {
    Field{"value", &My::MyGE::Name::value},
};
};
