// This file is generated by My::MySRefl::AutoRefl
 
#pragma once
 
#include <MySRefl/MySRefl.h>
 
template<>
struct My::MySRefl::TypeInfo<My::MyGE::Skybox>
    : My::MySRefl::TypeInfoBase<My::MyGE::Skybox>
{
  static constexpr AttrList attrs = {};
 
  static constexpr FieldList fields = {
    Field{"material", &My::MyGE::Skybox::material},
};
};
