// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template<>
struct My::MySRefl::TypeInfo<My::MyGE::WorldTime>
    : My::MySRefl::TypeInfoBase<My::MyGE::WorldTime>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"elapsedTime", &My::MyGE::WorldTime::elapsedTime},
        Field{"deltaTime", &My::MyGE::WorldTime::deltaTime},
    };
};

