// This file is generated by My::MySRefl::AutoRefl

#pragma once

#include <MySRefl/MySRefl.h>

template <>
struct My::MySRefl::TypeInfo<My::MyGE::Material>
    : My::MySRefl::TypeInfoBase<My::MyGE::Material> {
  static constexpr AttrList attrs = {};

  static constexpr FieldList fields = {
      Field{"shader", &My::MyGE::Material::shader},
      Field{"texture2Ds", &My::MyGE::Material::texture2Ds},
      Field{"textureCubes", &My::MyGE::Material::textureCubes},
  };
};
